'use client';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Activity, GitBranch, Layers, Search, ShieldCheck, Building2, CircleAlert, ChevronRight } from 'lucide-react';
import { approvalPresentation, type CommandSnapshot, type CommandView, type EvidenceState, type CommandRun, type CommandApproval } from '@/lib/command/model';

const views: { id: CommandView; label: string; icon: typeof Activity; title: string; description: string }[] = [
  { id: 'overview', label: 'Overview', icon: Activity, title: 'Decisions before activity.', description: 'Follow each exception to its business, policy and evidence. Unobserved health stays unknown.' },
  { id: 'runs', label: 'Runs', icon: GitBranch, title: 'Every action has a trail.', description: 'Inspect scope, policy and reconciliation before deciding the next safe step.' },
  { id: 'agents', label: 'Agents', icon: Layers, title: 'A narrow execution network.', description: 'Configuration describes the intended topology. Reachability needs an actual observation.' },
  { id: 'approvals', label: 'Approvals', icon: ShieldCheck, title: 'Authority bound to evidence.', description: 'Review the exact payload, consequence and expiry. This workspace executes no decisions.' },
  { id: 'businesses', label: 'Businesses', icon: Building2, title: 'Scope stays visible.', description: 'Inspect business context without silently changing the active Control workspace.' },
  { id: 'system', label: 'System', icon: CircleAlert, title: 'Evidence over green lights.', description: 'Services, ingress and audit observations remain distinct from configuration and activity.' },
];
const states: EvidenceState[] = ['ready', 'loading', 'empty', 'partial', 'stale', 'denied', 'disconnected', 'error', 'unknown'];
const stateCopy: Record<EvidenceState, [string, string]> = {
  ready: ['Snapshot available', 'Review provenance and timestamps before using this evidence.'],
  loading: ['Reading operational evidence', 'Waiting for the source. No counts or health conclusions are available yet.'],
  empty: ['No records in this snapshot', 'The source returned an empty result. This does not prove the fleet is healthy.'],
  partial: ['Some evidence is missing', 'Available records remain inspectable. Missing receipts and unavailable sources are not zero.'],
  stale: ['Snapshot is stale', 'Values describe the recorded snapshot, not current operation. Obtain a fresh authorized read before acting.'],
  denied: ['Evidence access denied', 'Your permitted scope could not be verified. No records are displayed and no broader read is attempted.'],
  disconnected: ['Command evidence is not connected', 'A platform evidence adapter has not been approved for this workspace. Configure access only after schema and role review.'],
  error: ['Evidence read failed', 'The source did not return a usable response. Health, workload and outcomes remain unknown.'],
  unknown: ['Operational state is unknown', 'There is no trustworthy observation from which to infer readiness or successful execution.'],
};
function Badge({ children, danger = false }: { children: ReactNode; danger?: boolean }) { return <span className={`xc-badge${danger ? ' xc-danger' : ''}`}>{children}</span>; }
function Panel({ title, detail, children }: { title: string; detail?: string; children: ReactNode }) { return <section className="xc-panel"><header><h2>{title}</h2>{detail && <p>{detail}</p>}</header>{children}</section>; }
function Datum({ label, children }: { label: string; children: ReactNode }) { return <div className="xc-datum"><dt>{label}</dt><dd>{children}</dd></div>; }

export function CommandWorkspace({ initialView, snapshot, initialSystemView = 'health' }: { initialView: CommandView; snapshot: CommandSnapshot; initialSystemView?: 'health' | 'webhooks' | 'audit' }) {
  const [view, setView] = useState(initialView);
  const [state, setState] = useState(snapshot.state);
  const [query, setQuery] = useState('');
  const [runId, setRunId] = useState(snapshot.runs[0]?.id ?? '');
  const [approvalId, setApprovalId] = useState(snapshot.approvals[0]?.id ?? '');
  const [businessId, setBusinessId] = useState(snapshot.businesses[0]?.id ?? '');
  const [agentId, setAgentId] = useState(snapshot.agents[0]?.id ?? '');
  const [systemView, setSystemView] = useState<'health' | 'webhooks' | 'audit'>(initialSystemView);
  const definition = views.find(v => v.id === view)!;
  const visible = ['ready', 'partial', 'stale'].includes(state);
  const businesses = visible ? snapshot.businesses : [];
  const runs = visible ? snapshot.runs : [];
  const approvals = visible ? snapshot.approvals : [];
  const incidents = visible ? snapshot.incidents : [];
  const agents = ['ready', 'partial', 'stale', 'disconnected', 'unknown'].includes(state) ? snapshot.agents : [];
  const run = runs.find(r => r.id === runId);
  const approval = approvals.find(a => a.id === approvalId);
  const business = businesses.find(b => b.id === businessId);
  const agent = agents.find(a => a.id === agentId);
  const now = snapshot.observedAt ?? new Date().toISOString();
  const matched = (text: string) => text.toLocaleLowerCase().includes(query.toLocaleLowerCase());
  const inspectRun = (id: string) => { setRunId(id); setView('runs'); setQuery(''); };
  const inspectBusiness = (id: string) => { setBusinessId(id); setView('businesses'); setQuery(''); };
  const inspectApproval = (id: string) => { setApprovalId(id); setView('approvals'); setQuery(''); };
  const changeView = (next: CommandView) => { setView(next); setQuery(''); };
  return <div className="xc-workspace" data-command-view={view}>
    <div className="xc-source" role="status"><span><strong>{snapshot.source === 'Synthetic' ? 'Synthetic · isolated review fixtures' : 'Source unavailable · no platform records loaded'}</strong><br />{snapshot.source === 'Synthetic' ? 'No customer evidence, live health or execution. All identifiers and timings are simulated.' : 'No service credentials, health probes or operational actions are used by this slice.'}</span><span className="xc-mono">{snapshot.observedAt ? `Fixed snapshot ${snapshot.observedAt}` : 'Observation —'}</span></div>
    <nav className="xc-nav" aria-label="Command sections">{views.map(v => <button key={v.id} aria-current={view === v.id ? 'page' : undefined} onClick={() => changeView(v.id)}><v.icon size={16} aria-hidden="true" />{v.label}</button>)}</nav>
    <header className="xc-heading"><div><p className="xc-eyebrow">Command / {definition.label}</p><h1>{definition.title}</h1><p>{definition.description}</p></div><Badge>Read-only inspection</Badge></header>
    <div className="xc-toolbar"><label className="xc-search"><Search size={16} aria-hidden="true" /><span className="sr-only">Search {definition.label.toLowerCase()}</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Search ${definition.label.toLowerCase()}`} /></label>{snapshot.source === 'Synthetic' && <label className="xc-state-picker">Synthetic evidence state<select value={state} onChange={e => setState(e.target.value as EvidenceState)}>{states.map(s => <option key={s} value={s}>{s}</option>)}</select></label>}</div>
    {state !== 'ready' && <section className={`xc-state xc-state-${state}`} data-state={state} aria-live="polite"><CircleAlert size={20} aria-hidden="true" /><div><h2>{stateCopy[state][0]}</h2><p>{stateCopy[state][1]}</p>{state === 'loading' && <div className="xc-skeleton" aria-hidden="true" />}</div></section>}
    {view === 'overview' && <>
      <div className="xc-metrics">{[['Business scope', businesses.length ? `${businesses.length} fixtures` : '—', 'Permitted snapshot only; not the total fleet'], ['Workload', '—', 'Queue pressure is unmeasured'], ['Provider health', 'Unknown', 'No provider observation'], ['Attention', incidents.length ? `${incidents.length} fixture items` : '—', 'Unavailable evidence is not a calm fleet']].map(([label, value, detail]) => <section key={label}><p>{label}</p><strong>{value}</strong><small>{detail}</small></section>)}</div>
      <div className="xc-columns"><Panel title="Attention decisions" detail="Grouped by cause; status is a recorded observation.">{incidents.filter(i => matched(`${i.title} ${i.cause}`)).map(i => <article className="xc-attention" key={i.id}><div><Badge danger={i.severity === 'critical'}>{i.severity} · {i.status}</Badge><h3>{i.title}</h3><p>{i.cause} / {snapshot.businesses.find(b => b.id === i.businessId)?.name}</p></div><button className="x-button" onClick={() => inspectRun(i.runId)}>Inspect trace<ChevronRight size={16} /></button></article>)}{!incidents.length && <Empty text="No incident evidence is available. This is not proof of no incidents." />}</Panel><Panel title="Business health" detail="Configuration, channel and outcome are separate facts.">{businesses.filter(b => matched(b.name)).map(b => <button className="xc-row" key={b.id} onClick={() => inspectBusiness(b.id)}><span><strong>{b.name}</strong><small>{b.health}</small><small>{b.channel}</small></span><ArrowUpRight size={18} aria-hidden="true" /></button>)}{!businesses.length && <Empty text="Business health requires an approved scoped source." />}<p className="xc-note">Security and pilot readiness remain NO-GO.</p></Panel></div>
    </>}
    {view === 'runs' && <div className="xc-split"><Panel title="Run stream" detail="Bounded snapshot · no automatic retries">{runs.filter(r => matched(`${r.title} ${r.id}`)).slice(0, 50).map(r => <button className="xc-row" aria-pressed={r.id === runId} key={r.id} onClick={() => setRunId(r.id)}><span><strong>{r.title}</strong><small>{r.state}</small><code>{r.id}</code></span><ChevronRight size={16} /></button>)}{!runs.filter(r => matched(`${r.title} ${r.id}`)).length && <Empty text="No matching runs in the available snapshot." />}</Panel><Panel title="Trace inspector" detail="Summary first. No hidden reasoning or secret payloads.">{run ? <RunInspector run={run} businessName={snapshot.businesses.find(b => b.id === run.businessId)?.name ?? 'Unknown business'} onBusiness={() => inspectBusiness(run.businessId)} onApproval={run.approvalId ? () => inspectApproval(run.approvalId!) : undefined} /> : <Empty text="Select a run when an authorized trace source is available." />}</Panel></div>}
    {view === 'agents' && <><Panel title="Configured topology" detail="Summoner routes domain work to sales; external execution belongs in Tool Gateway."><div className="xc-topology">{agents.filter(a => matched(a.name)).map(a => <button key={a.id} className="xc-node" aria-pressed={agentId === a.id} onClick={() => setAgentId(a.id)}><GitBranch size={20} aria-hidden="true" /><strong>{a.name}</strong><Badge>{a.configuration}</Badge><span>Reachability: {a.reachability}</span></button>)}</div><p className="xc-note">Topology from repository configuration. No network reachability or health is inferred.</p></Panel><Panel title="Capability inspector">{agent ? <dl className="xc-data-grid"><Datum label="Service">{agent.name}</Datum><Datum label="Role">{agent.role}</Datum><Datum label="Reachability">{agent.reachability}</Datum><Datum label="Version">{agent.version ?? 'Unknown'}</Datum><Datum label="Last run">{agent.lastRun ?? 'Unobserved'}</Datum><Datum label="Queue / failure rate">{agent.queue ?? 'Unknown'} / Unmeasured</Datum><Datum label="Allowed tools">{agent.tools.join(' · ') || 'None configured'}</Datum><Datum label="Risk ceiling">{agent.risk}</Datum></dl> : <Empty text="Service configuration is unavailable in this state." />}</Panel></>}
    {view === 'approvals' && <div className="xc-split"><Panel title="Decision history" detail="Read-only; no approve, reject or execute endpoint is called.">{approvals.filter(a => matched(`${a.title} ${a.status}`)).slice(0, 50).map(a => <button className="xc-row" key={a.id} aria-pressed={a.id === approvalId} onClick={() => setApprovalId(a.id)}><span><strong>{a.title}</strong><small>{a.risk}</small><Badge>{approvalPresentation(a, now)}</Badge></span><ChevronRight size={16} /></button>)}{!approvals.filter(a => matched(`${a.title} ${a.status}`)).length && <Empty text="No matching approval evidence is available." />}</Panel><Panel title="Decision inspector" detail="Approval must match the exact current payload.">{approval ? <ApprovalInspector approval={approval} now={now} onRun={() => inspectRun(approval.runId)} onBusiness={() => inspectBusiness(approval.businessId)} /> : <Empty text="An approval requires a verified business, action and version." />}</Panel></div>}
    {view === 'businesses' && <div className="xc-split"><Panel title="Scoped directory" detail="Only businesses in this snapshot; no global tenant assumption.">{businesses.filter(b => matched(b.name)).slice(0, 50).map(b => <button className="xc-row" key={b.id} aria-pressed={b.id === businessId} onClick={() => setBusinessId(b.id)}><span><strong>{b.name}</strong><small>{b.health}</small></span><ChevronRight size={16} /></button>)}{!businesses.filter(b => matched(b.name)).length && <Empty text="No matching businesses in the permitted snapshot." />}</Panel><Panel title="Business inspector">{business ? <><dl className="xc-data-grid"><Datum label="Business">{business.name}</Datum><Datum label="Channel">{business.channel}</Datum><Datum label="Configuration">{business.configuration}</Datum><Datum label="Outcome / freshness">Unverified / {snapshot.observedAt ?? 'Unknown'}</Datum></dl><div className="xc-inspector-actions">{runs.filter(r => r.businessId === business.id).map(r => <button className="x-button" key={r.id} onClick={() => inspectRun(r.id)}>Inspect {r.id}</button>)}<Link className="x-button" href="/dashboard">Open selected Control workspace<ArrowUpRight size={16} /></Link></div><p className="xc-note">This link uses the existing active-business session. It does not select this fixture or switch tenant. Use the authorized workspace selector for a real business.</p></> : <Empty text="Business context is unavailable. No cross-business fallback is used." />}</Panel></div>}
    {view === 'system' && <><nav className="xc-subnav" aria-label="System evidence">{(['health', 'webhooks', 'audit'] as const).map(s => <button key={s} aria-current={systemView === s ? 'page' : undefined} onClick={() => setSystemView(s)}>{s}</button>)}</nav><Panel title={systemView === 'health' ? 'Service observations' : systemView === 'webhooks' ? 'Ingress evidence' : 'Audit history'} detail="Unavailable source values never become successful checks.">{systemView === 'health' ? <><dl className="xc-data-grid"><Datum label="Database observation">Unavailable</Datum><Datum label="RLS / grants">Not verified by this UI</Datum><Datum label="WhatsApp / provider">Disconnected · no observation</Datum><Datum label="Migration compatibility">Requires environment audit</Datum><Datum label="Scheduler / queue">Unknown</Datum><Datum label="Security / pilot">NO-GO</Datum></dl><p className="xc-note">Configuration presence is not a readiness check. This page makes no diagnostic network calls.</p></> : systemView === 'webhooks' ? <Empty text="No verified webhook receipt source. A persisted message alone does not prove a valid signature, complete delivery or external outcome." /> : <>{runs.filter(r => matched(r.title)).map(r => <article key={r.id} className="xc-attention"><div><Badge>Receipt {r.receipt ? 'recorded' : 'unavailable'}</Badge><h3>{r.title}</h3><p>{r.receipt ?? 'No authoritative receipt · actor and timing shown in trace'}</p></div><button className="x-button" onClick={() => inspectRun(r.id)}>Inspect evidence</button></article>)}{!runs.length && <Empty text="No authorized audit records loaded. Empty history does not establish no activity." />}<p className="xc-note">Append-only receipt and audit authority remains in Phase 4B. Export requires an approved scoped evidence adapter; no fabricated export is offered.</p></>}</Panel></>}
    <footer className="xc-footer">{snapshot.source === 'Synthetic' ? 'Synthetic review only · no database records or customer evidence' : 'Evidence unavailable · no operational readiness claim'}<span>G-DISCOVERY / G-WEDGE: NOT PASSED</span></footer>
  </div>;
}
function Empty({ text }: { text: string }) { return <div className="xc-empty"><CircleAlert size={22} aria-hidden="true" /><p>{text}</p></div>; }
function RunInspector({ run, businessName, onBusiness, onApproval }: { run: CommandRun; businessName: string; onBusiness: () => void; onApproval?: () => void }) {
  return <><dl className="xc-data-grid"><Datum label="Business"><button className="xc-text-button" onClick={onBusiness}>{businessName} ↗</button></Datum><Datum label="Run state">{run.state}</Datum><Datum label="Policy">{run.policy}</Datum><Datum label="Approval">{onApproval ? <button className="xc-text-button" onClick={onApproval}>Inspect linked approval ↗</button> : 'No linked approval evidence'}</Datum><Datum label="Receipt">{run.receipt ?? 'Unavailable · not executed proof'}</Datum><Datum label="Retries">{run.retries} · provider commitment remains unverified</Datum></dl><ol className="xc-timeline">{run.steps.map((s, index) => <li key={`${run.id}-${index}`}><span className="xc-step-number">{index + 1}</span><div><div className="xc-step-title"><h3>{s.title}</h3><Badge>{s.state}</Badge></div><p>{s.summary}</p><small>{s.actor} · {s.at ?? 'Time unknown'} · {s.latencyMs === null ? 'Latency unknown' : `${s.latencyMs}ms`}</small><p className="xc-evidence">{s.evidence ?? 'Evidence unavailable'}</p></div></li>)}</ol><div className="xc-recovery"><h3>Recovery context</h3><p>{run.recovery}</p></div><details className="xc-details"><summary>Redacted identifiers</summary><code>{run.id} / {run.businessId}</code><p>No raw payload or secrets. Summary evidence does not expose hidden chain-of-thought.</p></details></>;
}
function ApprovalInspector({ approval, now, onRun, onBusiness }: { approval: CommandApproval; now: string; onRun: () => void; onBusiness: () => void }) {
  const status = approvalPresentation(approval, now);
  return <><div className="xc-approval-status"><Badge danger={['changed', 'expired', 'revoked', 'denied'].includes(status)}>{status}</Badge><strong>Not executable from this workspace</strong></div><dl className="xc-data-grid"><Datum label="Reason">{approval.reason}</Datum><Datum label="Risk / expiry">{approval.risk} / {approval.expiresAt}</Datum><Datum label="Payload hash"><code>{approval.hash}</code></Datum><Datum label="Approved hash"><code>{approval.approvedHash ?? 'No bound approval'}</code></Datum><Datum label="Impact">{approval.impact}</Datum><Datum label="Rollback">{approval.rollback}</Datum></dl><div className="xc-diff"><div><small>Before</small><p>{approval.before}</p></div><div><small>Proposed</small><p>{approval.after}</p></div></div><div className="xc-inspector-actions"><button className="x-button" onClick={onRun}>Inspect linked run</button><button className="x-button" onClick={onBusiness}>Inspect business scope</button></div><p className="xc-note">Changing a payload invalidates its approval. Expired or revoked decisions require fresh authority. Displaying an executed state is not a verified provider outcome.</p></>;
}
